public class Category {
    private int id; // Optional: If your database table has an ID field
    private String name;

    // Constructor
    public Category(int id, String name) {
        this.id = id;
        this.name = name;
    }

    // Constructor without ID (if ID is auto-generated by the database)
    public Category(String name) {
        this.name = name;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // Optional: toString method for easier debugging or display
    @Override
    public String toString() {
        return name;
    }
}